services:

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video_automation_odoo
    ports:
      - "8069:8069"
      - "8072:8072"
    env_file:
      - .env
    environment:
      HOST: 116.118.3.84
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
      - ./tmp:/tmp/video_work
    command:
      [
        "odoo",
        "-c",
        "/etc/odoo/odoo.conf",
        "--db_host=116.118.3.84",
        "--db_user=odoo",
        "--db_password=odoo",
        "--addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons",
      ]

volumes:
  odoo-web-data:
